version: 2
updates:
  # Python dependencies configuration
  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    allow:
      - dependency-type: "all"
    assignees:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      python-packages:
        patterns:
          - "*"
      security-updates:
        update-types:
          - "security"
    labels:
      - "dependencies"
      - "python"
      - "security"
    open-pull-requests-limit: 10
    target-branch: "main"
    versioning-strategy: "auto"
    ignore:
      - dependency-name: "python"
        versions: ["< 3.11.0"]

  # Node.js dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    allow:
      - dependency-type: "all"
    assignees:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      react-packages:
        patterns:
          - "react*"
          - "@types/react*"
        exclude-patterns:
          - "@testing-library/react*"
      mui-packages:
        patterns:
          - "@mui/*"
      security-updates:
        update-types:
          - "security"
    labels:
      - "dependencies"
      - "javascript"
      - "security"
    open-pull-requests-limit: 10
    target-branch: "main"
    versioning-strategy: "auto"
    ignore:
      - dependency-name: "node"
        versions: ["< 18.0.0"]

  # Docker dependencies configuration
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    allow:
      - dependency-type: "all"
    assignees:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      security-updates:
        update-types:
          - "security"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    open-pull-requests-limit: 5
    target-branch: "main"

  # GitHub Actions dependencies configuration
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    allow:
      - dependency-type: "all"
    assignees:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      security-updates:
        update-types:
          - "security"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
    open-pull-requests-limit: 5
    target-branch: "main"